<?xml version="1.0"?>

<robot name="scout_v2"  xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" /> 

    <!-- 属性封装 -->
    <xacro:property name="M_PI" value="3.14159"/>

    <xacro:property name="base_x_size" value="0.9250000" />
    <xacro:property name="base_y_size" value="0.380000" />
    <xacro:property name="base_z_size" value="0.210000" />

    <xacro:property name="wheelbase" value="0.498" />
    <xacro:property name="track" value="0.58306" />   <!-- track————车轮间距 -->
    <xacro:property name="wheel_vertical_offset" value="-0.0702" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />

    
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    
    <!-- 底盘的轮子 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/scout_wheel_type1.xacro" />
    <xacro:include filename="$(find scout_gazebo)/urdf/scout_wheel_type2.xacro" />
    <xacro:include filename="$(find scout_gazebo)/urdf/inertial.xacro" />
    <!-- <xacro:include filename="$(find scout_gazebo)/urdf/camera.xacro" /> -->
    <!-- <xacro:include filename="$(find scout_gazebo)/urdf/sensor_camera.xacro" /> -->
    
    <!-- D435i RGB-D相机相关 -->
    <!-- <xacro:include filename="$(find realsense_ros_gazebo)/xacro/depthcam.xacro"/>
    <xacro:realsense_d435 sensor_name="camera" parent_link="base_link" rate="30.0">
    <origin rpy="0 0 0" xyz="0 0 0.3"/>
    </xacro:realsense_d435> -->
    
   
    <xacro:include filename="$(find scout_gazebo)/urdf/laser_support.xacro" />

    <!-- 添加一个中间link，与水平面成30度夹角 - 这是固定的倾斜支架 -->
    <link name="tilt_link">
    <visual>
        <geometry>
        <sphere radius="0.005"/>  <!-- 小球标记倾斜点 -->
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="red">
            <color rgba="0.8 0.2 0.0 0.8" />
        </material>
    </visual>
    <inertial>
        <mass value="0.02"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1.8e-6" iyy="1.8e-6" izz="1.8e-6" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    </link>

    <!-- 固定关节，将tilt_link以-30度角固定在support上 -->
    <joint name="tilt_joint" type="fixed">
        <parent link="support"/>
        <child link="tilt_link"/>
        <origin xyz="0.1 0 ${support_length/2}" rpy="0 ${-M_PI/6} 0"/>  <!-- 绕y轴旋转-30度 -->
    </joint>

    <!-- 实体旋转轴 - 这是绕x轴旋转的圆柱轴 -->
    <link name="rotation_shaft">
    <visual>
        <geometry>
        <cylinder length="0.3" radius="0.02"/>  <!-- 长30cm，半径2cm的圆柱轴 -->
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0"/>  <!-- 旋转90度使圆柱沿x轴方向 -->
        <material name="metal">
            <color rgba="0.5 0.5 0.5 1.0" />  <!-- 金属灰色 -->
        </material>
    </visual>
    <collision>
        <geometry>
        <cylinder length="0.3" radius="0.02"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0"/>
    </collision>
    <inertial>
        <mass value="0.5"/>  <!-- 旋转轴质量 -->
        <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0"/>
        <inertia ixx="0.00375" iyy="0.00375" izz="0.0001" ixy="0" ixz="0" iyz="0"/>  <!-- 圆柱惯性矩 -->
    </inertial>
    </link>

    <!-- 旋转关节，使rotation_shaft绕tilt_link的x轴旋转 -->
    <joint name="velodyne_spin_joint" type="continuous">
        <parent link="tilt_link"/>
        <child link="rotation_shaft"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>  <!-- 绕x轴旋转 -->
        <limit effort="5.0" velocity="10.0"/>
        <dynamics damping="0.01" friction="0.01"/>
    </joint>

    <!-- 雷达安装平台 - 固定在旋转轴末端 -->
    <link name="velodyne_mount">
    <visual>
        <geometry>
        <cylinder length="0.02" radius="0.08"/>  <!-- 2cm厚的圆盘平台 -->
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="platform">
            <color rgba="0.2 0.2 0.2 1.0" />  <!-- 深灰色平台 -->
        </material>
    </visual>
    <collision>
        <geometry>
        <cylinder length="0.02" radius="0.08"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    </link>

    <!-- 固定关节，将velodyne_mount固定在旋转轴末端 -->
    <joint name="mount_to_shaft_joint" type="fixed">
        <parent link="rotation_shaft"/>
        <child link="velodyne_mount"/>
        <origin xyz="0.15 0 0" rpy="0 0 0"/>  <!-- 固定在旋转轴末端（x轴正方向15cm处）-->
    </joint>

    <!-- transmission (ros_control需要) #3 -->
    <transmission name="velodyne_spin_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="velodyne_spin_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="velodyne_spin_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
    </transmission>
    
     <!-- VLP16 激光雷达 -->
    <xacro:arg name="gpu" default="false"/>
    <xacro:property name="gpu"  value="$(arg gpu)"/>
     <xacro:arg name="organize_cloud" default="true"/>
    <xacro:property name="organize_cloud" value="$(arg organize_cloud)"/>

    <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
    <!-- 把雷达挂在 mount 上 -->
    <xacro:VLP-16 parent="velodyne_mount" name="velodyne" topic="/velodyne_points"
                  organize_cloud="${organize_cloud}" hz="10" samples="440" gpu="${gpu}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:VLP-16>
    <!--<xacro:VLP-16 parent="support" name="velodyne" topic="/velodyne_points" organize_cloud="${organize_cloud}" hz="10" samples="440" gpu="${gpu}">
          <origin xyz="0.2 0 ${support_length/2}" rpy="0 0 0" /> 
    </xacro:VLP-16>-->

    <!-- IMU 模块 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/imu.xacro"/>
    <xacro:imu sensor_name="imu" parent_link="base_link">
    <origin rpy="0 0 0" xyz="-0.03 0 ${base_z_size/2}"/>   <!--0.105  -->
    </xacro:imu>

    <!-- 机器人导航控制模块 -->
    <xacro:include filename="$(find scout_gazebo)/urdf/move.xacro" />

    <!-- Base link  底盘 -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <!--<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>-->
                <mesh filename="package://scout_gazebo/meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0.0008" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <link name="inertial_link">
        <inertial>
            <mass value="40" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- 宏  Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:scout_wheel_type1 wheel_prefix="front_right">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="front_left">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type2>
    <xacro:scout_wheel_type1 wheel_prefix="rear_left">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:scout_wheel_type1>
    <xacro:scout_wheel_type2 wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0" />
    </xacro:scout_wheel_type2>

    <!-- gazebo_ros_control 插件 #5 -->
    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
        <!-- 提高控制频率，降低周期值 -->
        <controlPeriod>0.0025</controlPeriod>  <!-- 1/400秒 = 0.0025秒 -->
      </plugin>
      
      <!-- 提高joint_state_publisher更新频率到400Hz --> <!--将指定的joints发布为/joint_states的话题-->
      <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
        <jointName>velodyne_spin_joint</jointName> 
        <updateRate>400</updateRate>  <!-- 从50Hz提高到400Hz -->
      </plugin>
    </gazebo>
    
    <!-- 添加gazebo标签，指定关节物理属性 #7 -->
    <gazebo reference="velodyne_spin_joint">
      <provideFeedback>true</provideFeedback>
      <implicitSpringDamper>1</implicitSpringDamper>
    </gazebo>

    <!-- 优化Gazebo物理属性 -->
    <!-- <gazebo>
      <physics type="ode">
        <max_step_size>0.001</max_step_size> 
        <real_time_factor>1.0</real_time_factor>
        <real_time_update_rate>1000</real_time_update_rate> 
      </physics>
    </gazebo> -->

</robot>
